# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTNi8m7MLzFPq0UFpq_knhwYKjB6jWBR
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import pickle
# 
# # Load the popular books dataframe
# # Assuming popular_books_df is saved as a pickle file after being generated in the notebook
# try:
#     popular_books_df = pd.read_pickle('popular_books_df.pkl')
# except FileNotFoundError:
#     st.error("Error: 'popular_books_df.pkl' not found. Please make sure you have run the notebook to generate and save this file.")
#     st.stop()
# 
# st.title('Book Recommendation System (Popularity-Based)')
# 
# st.write('This app recommends popular books based on average ratings and minimum rating count.')
# 
# # Get the number of recommendations from the user
# num_recommendations = st.slider('Select the number of recommendations:', 5, 50, 10)
# 
# # Function to get popularity-based recommendations
# def get_popularity_recommendations(n=10):
#     """
#     Returns the top n popular books based on the pre-calculated popular_books_df.
#     """
#     return popular_books_df.head(n)
# 
# # Display recommendations
# if popular_books_df is not None:
#     st.subheader(f'Top {num_recommendations} Popular Books:')
#     recommendations = get_popularity_recommendations(num_recommendations)
#     st.dataframe(recommendations)
# else:
#     st.write("Popular books data not available.")
# 
# st.write("Note: This is a simple popularity-based model. For personalized recommendations, a collaborative filtering model would be needed.")